# Generated by Django 3.1.4 on 2020-12-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imige',
            new_name='image',
        ),
    ]
